### ISSUE TITLE
Cannot call value of non-function type 'String'

### ISSUE THREAD

**Issue by PhoenixLeeSin** [DingSoung/Extension#2]
private class func browsing_contextController() -> (NSObject.Type)? {
        guard let str = "YnJvd3NpbmdDb250ZXh0Q29udHJvbGxlcg==".base64Decode else { assertionFailure(); return nil }
        // str: "browsingContextController"
        guard let obj =  WKWebView().value(forKey: str) else { return nil }
        
        return type(of: obj) as? NSObject.Type
    }
return 这个地方报错Cannot call value of non-function type 'String'
大佬看一下？

**Comment by song-react** [comment]
贴代码看看

**Comment by PhoenixLeeSin** [comment]
> 贴代码看看
自己改好了 -。-
